import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/widgets/header/ui/Header";
const myFont = localFont({
  src: "./fonts/PretendardVariable.woff2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr" className={myFont.className}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
