import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/shared/styles/globals.css";
import Header from "@/widgets/header/ui/Header";
import { ModalContainer } from "@/shared/ui/ModalContainer/ModalContainer";
const myFont = localFont({
  src: "../shared/fonts/PretendardVariable.woff2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr" className={myFont.className}>
      <body className="bg-[#1c1c22] pt-[70px] md:pt-[80px] xl:pt-[100px]">
        <Header />
        {children}
        <div id="modal-root" />
        <ModalContainer />
      </body>
    </html>
  );
}
