export const chats = [
  {
    chatId: 501,
    postingId: 101,
    postingTitle: "맥북 프로 16인치 판매",
    role: "buyer",
    lastMessage: "가격 조정이 가능할까요?",
    createdAt: "2025-10-24T09:30:00Z",
    status: "RESERVED",
    otherId: 33,
    otherNick: "홍길동",
    otherImage: "",
  },
  {
    chatId: 502,
    postingId: 102,
    postingTitle: "아이패드 미니 판매",
    role: "seller",
    lastMessage: "상품 상태에 대해 궁금한 점이 있습니다.",
    createdAt: "2025-10-23T21:00:00Z",
    status: "SOLD",
    otherId: 35,
    otherNick: "김민수",
    otherImage: "",
  },
  {
    chatId: 503,
    postingId: 103,
    postingTitle: "닌텐도 스위치 OLED 팝니다",
    role: "buyer",
    lastMessage: "직거래 가능한가요?",
    createdAt: "2025-10-22T15:10:00Z",
    status: "ACTIVE",
    otherId: 36,
    otherNick: "이서준",
    otherImage: "",
  },
  {
    chatId: 504,
    postingId: 104,
    postingTitle: "에어팟 프로 2세대 판매",
    role: "seller",
    lastMessage: "혹시 구성품은 모두 있나요?",
    createdAt: "2025-10-21T13:45:00Z",
    status: "ACTIVE",
    otherId: 37,
    otherNick: "박지현",
    otherImage: "",
  },
  {
    chatId: 505,
    postingId: 105,
    postingTitle: "게이밍 의자 판매합니다",
    role: "buyer",
    lastMessage: "의자 상태 괜찮나요?",
    createdAt: "2025-10-19T10:20:00Z",
    status: "RESERVED",
    otherId: 38,
    otherNick: "최민재",
    otherImage: "",
  },
];
